/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencvtest_NativeLibrary */

#ifndef _Included_com_example_opencvtest_NativeLibrary
#define _Included_com_example_opencvtest_NativeLibrary

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencvtest_NativeLibrary
 * Method:    testOpenCV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opencvtest_NativeLibrary_testOpenCV
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
